const fs = require('fs');

const content = `export const PERMISSIONS = {
  // DASHBOARD
  DASHBOARD_VIEW: 'dashboard.view',
  
  // POS
  POS_VIEW: 'pos.view',
  POS_CREATE: 'pos.create',
  POS_EDIT: 'pos.edit',
  POS_DELETE: 'pos.delete',
  POS_MANAGE: 'pos.manage',
  POS_CREATE_ORDER: 'pos.create_order',
  POS_CANCEL_ORDER: 'pos.cancel_order',
  POS_REFUND: 'pos.refund',
  POS_APPLY_DISCOUNT: 'pos.apply_discount',
  
  // ORDERS
  ORDERS_VIEW: 'orders.view',
  ORDERS_CREATE: 'orders.create',
  ORDERS_EDIT: 'orders.edit',
  ORDERS_DELETE: 'orders.delete',
  ORDERS_MANAGE: 'orders.manage',
  
  // KITCHEN
  KITCHEN_VIEW: 'kitchen.view',
  
  // MENU
  MENU_VIEW: 'menu.view',
  MENU_CREATE: 'menu.create',
  MENU_EDIT: 'menu.edit',
  MENU_DELETE: 'menu.delete',
  MENU_MANAGE: 'menu.manage',
  
  // INVENTORY
  INVENTORY_VIEW: 'inventory.view',
  INVENTORY_CREATE: 'inventory.create',
  INVENTORY_EDIT: 'inventory.edit',
  INVENTORY_DELETE: 'inventory.delete',
  INVENTORY_MANAGE: 'inventory.manage',
  
  // PURCHASES
  PURCHASES_VIEW: 'purchases.view',
  PURCHASES_CREATE: 'purchases.create',
  PURCHASES_EDIT: 'purchases.edit',
  PURCHASES_DELETE: 'purchases.delete',
  PURCHASES_MANAGE: 'purchases.manage',
  
  // SUPPLIERS
  SUPPLIERS_VIEW: 'suppliers.view',
  SUPPLIERS_CREATE: 'suppliers.create',
  SUPPLIERS_EDIT: 'suppliers.edit',
  SUPPLIERS_DELETE: 'suppliers.delete',
  SUPPLIERS_MANAGE: 'suppliers.manage',
  
  // CUSTOMERS
  CUSTOMERS_VIEW: 'customers.view',
  CUSTOMERS_CREATE: 'customers.create',
  CUSTOMERS_EDIT: 'customers.edit',
  CUSTOMERS_DELETE: 'customers.delete',
  CUSTOMERS_MANAGE: 'customers.manage',
  
  // LOYALTY
  LOYALTY_VIEW: 'loyalty.view',
  LOYALTY_CREATE: 'loyalty.create',
  LOYALTY_EDIT: 'loyalty.edit',
  LOYALTY_DELETE: 'loyalty.delete',
  LOYALTY_MANAGE: 'loyalty.manage',
  
  // DISCOUNTS
  DISCOUNTS_VIEW: 'discounts.view',
  DISCOUNTS_CREATE: 'discounts.create',
  DISCOUNTS_EDIT: 'discounts.edit',
  DISCOUNTS_DELETE: 'discounts.delete',
  DISCOUNTS_MANAGE: 'discounts.manage',
  
  // EXPENSES
  EXPENSES_VIEW: 'expenses.view',
  EXPENSES_CREATE: 'expenses.create',
  EXPENSES_EDIT: 'expenses.edit',
  EXPENSES_DELETE: 'expenses.delete',
  EXPENSES_MANAGE: 'expenses.manage',
  
  // CASH
  CASH_VIEW: 'cash.view',
  CASH_CREATE: 'cash.create',
  CASH_EDIT: 'cash.edit',
  CASH_DELETE: 'cash.delete',
  CASH_MANAGE: 'cash.manage',
  
  // STAFF
  STAFF_VIEW: 'staff.view',
  STAFF_CREATE: 'staff.create',
  STAFF_EDIT: 'staff.edit',
  STAFF_DELETE: 'staff.delete',
  STAFF_MANAGE: 'staff.manage',
  
  // REPORTS
  REPORTS_VIEW: 'reports.view',
  REPORTS_EXPORT: 'reports.export',
  
  // SETTINGS
  SETTINGS_VIEW: 'settings.view',
  SETTINGS_CREATE: 'settings.create',
  SETTINGS_EDIT: 'settings.edit',
  SETTINGS_DELETE: 'settings.delete',
  SETTINGS_MANAGE: 'settings.manage',
  
  // ROLES
  ROLES_VIEW: 'roles.view',
  ROLES_CREATE: 'roles.create',
  ROLES_EDIT: 'roles.edit',
  ROLES_DELETE: 'roles.delete',
  ROLES_MANAGE: 'roles.manage',
  
  // AUDIT
  AUDIT_VIEW: 'audit.view',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  OWNER: Object.values(PERMISSIONS) as Permission[],
  MANAGER: [
    PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.POS_VIEW, PERMISSIONS.POS_CREATE_ORDER,
    PERMISSIONS.POS_CANCEL_ORDER, PERMISSIONS.POS_APPLY_DISCOUNT, 
    PERMISSIONS.ORDERS_VIEW, PERMISSIONS.ORDERS_CREATE, PERMISSIONS.ORDERS_EDIT,
    PERMISSIONS.ORDERS_MANAGE, PERMISSIONS.KITCHEN_VIEW, 
    PERMISSIONS.MENU_VIEW, PERMISSIONS.MENU_CREATE, PERMISSIONS.MENU_EDIT, PERMISSIONS.MENU_MANAGE,
    PERMISSIONS.INVENTORY_VIEW, PERMISSIONS.INVENTORY_CREATE, PERMISSIONS.INVENTORY_EDIT, PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.PURCHASES_VIEW, PERMISSIONS.PURCHASES_CREATE, PERMISSIONS.PURCHASES_EDIT, PERMISSIONS.PURCHASES_MANAGE,
    PERMISSIONS.SUPPLIERS_VIEW, PERMISSIONS.SUPPLIERS_CREATE, PERMISSIONS.SUPPLIERS_EDIT, PERMISSIONS.SUPPLIERS_MANAGE,
    PERMISSIONS.CUSTOMERS_VIEW, PERMISSIONS.CUSTOMERS_CREATE, PERMISSIONS.CUSTOMERS_EDIT, PERMISSIONS.CUSTOMERS_MANAGE,
    PERMISSIONS.LOYALTY_VIEW, PERMISSIONS.DISCOUNTS_VIEW, PERMISSIONS.DISCOUNTS_MANAGE,
    PERMISSIONS.EXPENSES_VIEW, PERMISSIONS.EXPENSES_CREATE, PERMISSIONS.EXPENSES_EDIT, PERMISSIONS.EXPENSES_MANAGE, 
    PERMISSIONS.CASH_VIEW, PERMISSIONS.CASH_MANAGE, PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_EXPORT, PERMISSIONS.SETTINGS_VIEW, PERMISSIONS.SETTINGS_EDIT, PERMISSIONS.AUDIT_VIEW,
  ],
  CASHIER: [
    PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.POS_VIEW, PERMISSIONS.POS_CREATE_ORDER,
    PERMISSIONS.POS_CANCEL_ORDER, PERMISSIONS.POS_APPLY_DISCOUNT, PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW, PERMISSIONS.CUSTOMERS_CREATE, PERMISSIONS.CUSTOMERS_EDIT,
    PERMISSIONS.CASH_VIEW, PERMISSIONS.CASH_MANAGE, PERMISSIONS.REPORTS_VIEW,
  ],
  WAITER: [
    PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.POS_VIEW, PERMISSIONS.POS_CREATE_ORDER,
    PERMISSIONS.ORDERS_VIEW, PERMISSIONS.CUSTOMERS_VIEW,
  ],
  KITCHEN: [
    PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.KITCHEN_VIEW, PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
  ],
  INVENTORY_MANAGER: [
    PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.INVENTORY_VIEW, PERMISSIONS.INVENTORY_CREATE,
    PERMISSIONS.INVENTORY_EDIT, PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.PURCHASES_VIEW, PERMISSIONS.PURCHASES_CREATE, PERMISSIONS.PURCHASES_EDIT, PERMISSIONS.PURCHASES_MANAGE, 
    PERMISSIONS.SUPPLIERS_VIEW, PERMISSIONS.SUPPLIERS_CREATE, PERMISSIONS.SUPPLIERS_EDIT, PERMISSIONS.SUPPLIERS_MANAGE,
    PERMISSIONS.REPORTS_VIEW,
  ],
  ACCOUNTANT: [
    PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.ORDERS_VIEW, 
    PERMISSIONS.EXPENSES_VIEW, PERMISSIONS.EXPENSES_CREATE, PERMISSIONS.EXPENSES_EDIT, PERMISSIONS.EXPENSES_MANAGE, 
    PERMISSIONS.CASH_VIEW, PERMISSIONS.CASH_MANAGE,
    PERMISSIONS.REPORTS_VIEW, PERMISSIONS.REPORTS_EXPORT, PERMISSIONS.PURCHASES_VIEW,
    PERMISSIONS.AUDIT_VIEW,
  ],
};
`;

fs.writeFileSync('server/src/utils/permissions.ts', content);
